---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

# set up -----------------------------

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")

# library(devtools)
# remotes::install_github("catalystcalifornia/rdaCharts") 
library(rdaCharts)
library(stringr)
library(htmltools) 
library(htmlwidgets)
library(gtExtras)
library(gt)
#connect to postgres

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull analysis table for visualizing


df<-dbGetQuery(con, "SELECT * FROM report_traffic_result_stop")%>%
  mutate(stop_result_simple = str_to_title(stop_result_simple))


```

```{r, include=FALSE}

# Set up embed info------------------

# create caption 

sourcenote<-"Catalyst California calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made by officers in 2022."

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption_text <- paste("<br>", sourcenote, methodnote)

# create tooltip text

tooltip_text <- "Out of 100 officer-initiated traffic stops made by Fresno PD,  <b>{point.rate:.1f}%</b> resulted in <b>{point.stop_result_simple}</b>, or a total of <b>{point.count:.1f}</b> stops."

# visualize t--------------------------



chart<-rdaBubblepop(
  df,
  "stop_result_simple",
  "rate",
  "count",
  title = "The Majority of Traffic Stops made by Fresno PD Result in a Citation",
  subtitle = "Percent of officer-initiated traffic stops by stop result",
  tooltip_text = tooltip_text,
  caption = caption_text,
  export_data_label = list(pointFormat='{point.rate:.1f}%') 
)

```

```{r, echo=FALSE}

chart

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>