---
title: ""
output:
  html_document:
    includes:
      in_header: header.html
---

```{r, include=FALSE}
# Generate header.html with CSS if running standalone
if (is.null(knitr::opts_knit$get("child"))) {
  css_content <- readLines("../fbhc_brandguide.css")
  writeLines(paste0("<style>\n", paste(css_content, collapse="\n"), "\n</style>"), "header.html")
}
```

```{r, include=FALSE}

# set up -----------------------------
library(RPostgreSQL)
remotes::install_github("catalystcalifornia/rdaCharts", upgrade="never")
library(rdaCharts)
library(htmltools) 

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull and clean analysis tables for visualizing ----

df_p<-dbGetQuery(con, "SELECT * FROM report_traffic_race")

dbDisconnect(con)
```

```{r, include=FALSE}
# prep-data

# filter groups being visualized and select rate and counts to be visualized
df<-df_p%>%filter(race %in% c("nh_white","latinx","nh_asian_wo_sa","aian","nhpi","nh_multiracial","nh_black","sswana"))%>%
  select(race,traffic_count,pop_count,pop_1k_rate)%>%
  filter(traffic_count>=5)%>%
  arrange(-pop_1k_rate)

# create race label
df<-df%>%mutate(race_label = case_when(
    race == 'latinx' ~ "Latinx", 
    race =='nh_white' ~ 'White',
    race =='nh_black' ~ 'Black',
    race == 'nh_asian_wo_sa' ~ 'Asian',
   race == 'nh_multiracial' ~ 'Multiracial',
    race == 'aian' ~ 'AIAN',
    race == 'nhpi' ~ 'NHPI',
    race == 'sswana' ~ 'SWANA/SA', 
    TRUE ~ as.character(race)))

```

```{r, include=FALSE}
# prep-chart --------------------------
sourcenote<-"Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made by officers in 2022. Less than 5 people Fresno PD perceived as NHPI or Multiracial were stopped in officer-initiated traffic stop in 2022. For data masking purposes the data for these groups is suppressed from this chart."

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption_text <- "Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. Analysis covers all officer-initiated traffic stops in 2022. Groups with <5 stops (NHPI, Multiracial) were excluded. Race/ethnicity: AIAN=American Indian/Alaska Native, NHPI=Native Hawaiian/Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern)/North African/South Asian."#paste(sourcenote, methodnote,racenote)

tooltip_text <- "Fresno PD stopped <b>{point.pop_1k_rate:.1f}</b> people they perceived as <b>{point.race_label}</b> for traffic reasons for every 1K {point.race_label} people in Fresno City. A total of <b>{point.traffic_count:.0f}</b> people stopped."

chart_race<-rdaBubblepop(
  df,
  "race_label",
  "pop_1k_rate",
  "traffic_count",
  theme="theme_fbhc",
  title="Fresno PD Disproportionately Stops People They Perceive as Black or SWANA/SA For Traffic Reasons",
  subtitle="Officer-initiated traffic stops by perceived race per 1K people of same race",
  tooltip_text=tooltip_text,
  caption=caption_text,
  export_data_label=list(pointFormat='{point.pop_1k_rate:.1f} per 1K')) 

```

```{r, echo=FALSE}

chart_race

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>