---
title: ""
output:
  html_document:
    includes:
      in_header: "../header.html"
    mathjax: null
---

```{r, include=FALSE}
# Check if document is being run as a child, if yes don't apply styling again
is_child <- !is.null(knitr::opts_knit$get("parent.frame"))
if (is_child) {
  knitr::opts_chunk$set(include = FALSE)
}
```

```{r, include=FALSE}

# set up -----------------------------
library(RPostgreSQL)
library(devtools)
# remotes::install_github("catalystcalifornia/rdaCharts", upgrade="never") 
library(rdaCharts)
library(stringr)
library(htmltools)
library(purrr) # facet charts

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull analysis table for visualizing
df<-dbGetQuery(con, "SELECT * FROM report_traffic_result_citation_race")%>%
  mutate(statute_literal_25 = str_to_title(statute_literal_25))%>%
  mutate(statute_literal_25= case_when(statute_literal_25 == "Opr Veh:window Obstructed" ~ "Obstructed Window",
                                       statute_literal_25 == "Drive W/O License" ~ "Driving Without License",
                                       statute_literal_25 == "No Reg:veh/Trailer/Etc" ~ "No Vehicle Registration",
                                       statute_literal_25 == "Use Cellph W/Driv W/O Hfd" ~ "Using Cellphone Without Handheld Device",
                                       statute_literal_25 == "Unsafe Speed:prevail Cond" ~ "Unsafe Speed while Driving Vehicle", 
                                       .default = statute_literal_25))%>%
  
   filter(grepl("Obstructed Window|No Vehicle Registration", statute_literal_25)) %>%
  
   mutate(race = case_when(
    race == 'latinx' ~ "Latinx",
    race =='nh_white' ~ 'White',
    race =='nh_black' ~ 'Black',
    race == 'aian_aoic' ~ 'AIAN',
    race == 'nhpi_aoic' ~ 'NHPI',
    race == 'nh_multiracial' ~ 'Multiracial',
    race == 'sswana_aoic' ~ 'SWANA/SA',
    race=='nh_asian' ~ 'Asian',
    TRUE ~ as.character(race)))%>%
  filter(!grepl("nh_sswana|nh_aian|nh_nhpi", race))

# Aggregate the citations 'use of cellphone w drive without hfd' and 'no hnd hld device w/ drive' as they seem to basically be the same thing
# split up separate dfs for each denominator option
df_race<-df%>%
  filter(denom=="citation_race" )%>%
  group_by(race)%>%
  filter(total>=5)

df_result<-df%>%
  filter(denom=="citation_result")%>%
  group_by(race)%>%
  filter(count>=5)

# visualize DENOM 1: RACE--------------------------
# create title
title_text <- "Officers Show More Bias in Citations Unrelated to Public Safety"

# create caption 
sourcenote<-"Catalyst California calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis covers all officer-initiated traffic stops in 2022 that resulted in a citation. Groups with <5 stops (NHPI and AIAN) are excluded from the chart."

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption_text <- paste("<br>", racenote, sourcenote, methodnote)

# create tooltip text
tooltip_text <- "Out of 100 citations Fresno PD gave to people perceived as <b>{point.race}</b>, <b>{point.rate:.1f}%</b> were for <b>{point.statute_literal_25}</b>, or a total of <b>{point.count:f}</b> people cited."

# get rdaCharts theme for custom chart
data(theme_options)
list2env(theme_options, envir = .GlobalEnv)

```


```{r define-visual, echo=FALSE, include=FALSE, message=FALSE}

# TESTING FACETED HIGHCHARTER GRAPHS: RACE DENOMINATOR
list_of_plots <- map(unique(df_race$statute_literal_25), function(x) {
  filtered_data <- df_race %>%
    filter(statute_literal_25 == x) %>%
    arrange(desc(rate))%>%  # Sort by descending y-values
    mutate(bar_color = ifelse(race == "White",  "#053451","#FDB913"))  # Custom color for "White"  # Sort by descending y-values
  
  if (nrow(filtered_data) == 0) {
    return(NULL)  # Skip this group if there are no rows
  }
  
  highchart() %>%
    
    hc_add_series(filtered_data, 
                  "bar", 
                  hcaes(x = race, 
                        y = rate, 
                        color = bar_color),
                  showInLegend = FALSE) %>% 

    hc_plotOptions(column = list(stacking = "normal")) %>% 
    hc_add_theme(theme_fbhc) %>%
    hc_subtitle(text = paste0("Citations given for ",x," out of citations received by race"),
                style = list(
                  fontSize = "16px",
                  lineHeight = "22px")) %>%
    hc_yAxis(title = list(text = "Percent (%)",
                          style = list(
                            color = "#0A0A0A"
                          )),
             labels= list(style = list(
                            fontSize = "12px",
                            color = "#0A0A0A"),
                          overflow = "justify"))%>%
    hc_xAxis(title = list(text = ""),
             labels= list(position="bottom",
                          style = list(
                            fontSize = "12px"),
                          overflow = "justify"),
             type = "category")%>%
    hc_tooltip(headerFormat='', # removes series label from top of tooltip
               pointFormat = tooltip_text,
               outside = TRUE,
               useHTML=TRUE,
               style = list(fontSize = "14px")) %>%
    hc_chart(
      height = 600,
      reflow = TRUE,
      marginLeft = 80,
      marginRight = 80) %>%
    hc_exporting(
      enabled = TRUE,
      sourceWidth=900,
      sourceHeight=600,
      chartOptions=list(
        title = list(
          text = title_text,
          style = list(
            color = "#0A0A0A",
            fontSize = "21px",
            lineHeight = "28px",
            fontFamily = "Montserrat",
        fontWeight = "800"),
        align = "left"),
        caption = list(
          text = caption_text,
          style = list(
            fontSize = "12px",
            lineHeight = "18px"),
          align = "left",
          y = 15),
        plotOptions=list(
          series=list(
            dataLabels=list(
              enabled=TRUE,
              format = '{point.rate:.1f}',
              style = list(fontSize = "14px"))))),
      filename = paste0("Citations given for ",x," out of citations received by race","_Catalyst California, catalystcalifornia.org, ", format(Sys.Date(), "%Y"), "."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV'))))
})
```

```{r, echo=FALSE}
# Display chart

browsable(
  tagList(
    # Main title
    tags$text(title_text, 
              class="highcharts-title",
              style=css(
                color="#0A0A0A",
                font.size="21px",
                line.height="28px",
                font.family="Montserrat",
                font.weight="800",
                text.align="left",
                fill="#0A0A0A")),
    # Faceted charts
    list_of_plots %>% 
      hw_grid(rowheight = 450)))

```
<span class="highcharts-caption" data-z-index="4" style="font-family: 'Open Sans'; font-size: 12px; white-space: normal; margin-left: 0px; margin-top: 0px; left: 10px; top: 513px; color: rgb(10, 10, 10); font-weight: 400; text-align: left; line-height: 18px; width: 100%; display: block;">Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. Analysis covers all officer-initiated traffic stops in 2022 that resulted in a citation. Groups with <5 stops (NHPI and AIAN) are excluded from the chart. Race/ethnicity: SWANA/SA=Southwest Asian (Middle Eastern)/North African/South Asian.</span>

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>
