---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

# set up -----------------------------
library(RPostgreSQL)
library(purrr)
source("W:\\RDA Team\\R\\credentials_source.R")
# library(devtools)
 # remotes::install_github("catalystcalifornia/rdaCharts")
library(rdaCharts)

# connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("eci_fresno_ripa")

# Import data
# Get df of stop_ids for officer-initiated stops
ois_stops <- dbGetQuery(con, "SELECT * FROM data.rel_stops") %>% 
  filter(call_for_service==0) %>%
  select(stop_id)

# Get df of officer-initiated stops where people stopped just for traffic violations
ois_traffic <- dbGetQuery(con, "SELECT * FROM data.rel_persons_reason") %>%
  filter(reason=='Traffic violation') %>%
  select(stop_id,person_number,reason) %>%
  filter(stop_id %in% ois_stops$stop_id)

time <- dbGetQuery(con, "SELECT * FROM data.rel_stop_duration_capped")
p_races <- dbGetQuery(con, "SELECT * FROM data.rel_races_recode")
races <- dbGetQuery(con, "SELECT * FROM data.rel_stops_race")
p_results <- dbGetQuery(con, "SELECT * FROM data.rel_persons_result")
summary <- dbGetQuery(con, "SELECT * FROM data.report_timespent_traffic_race")

dbDisconnect(con)
```


```{r, include=FALSE}
# Stop universe selection and prep ----
# join race, result, and capped time
ois_traffic_race <- ois_traffic %>%
  left_join(p_races) %>%
  select(-race_count_re) %>%
  left_join(time) %>%
  left_join(p_results) %>%
  # add bipoc column 
# ois_traffic_race <- ois_traffic_race %>%
  mutate(bipoc=
           ifelse(nh_race=='nh_white', 'White', 'People of Color'),
         bipoc_label=
           ifelse(nh_race=='nh_white', 'White', 'a Person of Color')) %>%
  mutate(bipoc_flag=
           ifelse(bipoc=='People of Color', 1, 0))

# filter just for stops that resulted in one or more of the three: citation for infraction, warning, no action
target <- list("citation for infraction", "no action", "warning verbal or written")

# stop_result_list is not an actual list - need to convert and then can create  
# column that checks if elements in that list are not in our target list 
df <- ois_traffic_race %>%
  # will use eval(parse()) to convert to list, but need to reformat single result stops to have "c()" syntax
  mutate(stop_result_list2 = case_when(unique_stop_result_count==1 ~ paste0('c("', stop_result_list, '")'),
                                       .default = stop_result_list)) %>%
  # convert to list type (in View will still say character - 
  # can confirm with this code: typeof(df[1450, "stop_result_list3"]) VS typeof(df[1450, "stop_result_list"]) )
  mutate(stop_result_list3 = map(stop_result_list2, ~eval(parse(text=.x)))) %>%
  # actual check: returns TRUE if any of the elements in stop_result_list3 are not in our target list
  mutate(target_check = map_lgl(stop_result_list3, ~any(!(. %in% target)))) %>%
  # filter for only stops where all results are in target list
  filter(target_check == FALSE) %>%
  select(-c(stop_result_list2, stop_result_list3, target_check))

cor.test(df$bipoc_flag, df$stop_duration_capped)
# significantly correlated, p-value = 0.008005
# 95 percent confidence interval:
#  0.01035004 0.06886528

```

```{r, include=FALSE}

# visualize--------------------------
## COLORS ##
papaya <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"

 ## FONTS ##
main_font <- "Inter"
regular_font_weight <- 400
black_font_weight <- 800
semi_bold_font_weight <- 600


##### highchart theme #####
cc_theme <- hc_theme(
  colors = c(meteorite, lavender, papaya, peridot),
  chart = list(
    backgroundColor = alabaster,
    style = list(
      fontFamily = main_font, # font_subtitle
      color=alabaster)),
  title = list(widthAdjust = -50,
               style = list(
                 color = black,
                 fontFamily = main_font, # font_title
                 fontWeight = black_font_weight,
                 textAlign="left",
                 fontSize='21px'),
                 align = "left"),
  subtitle = list(
    style = list(
      color = black,
      fontFamily = main_font, # font_subtitle
      fontWeight = regular_font_weight,
      fontSize='14px'),
      align='left'),
  caption = list(
    style = list(
      color = black,
      fontFamily = main_font, # font_caption
      fontWeight = regular_font_weight,
      fontSize = "10px",
      textAlign = "left",
      width = 50),
    useHTML = TRUE,
    floating = FALSE),
  xAxis=list(
    labels=list(
      style=list(
        color=black,
        fontFamily = main_font, # font_x_label
        fontWeight = semi_bold_font_weight,
        width=120,  #argument to modify the width of the labels
        min=0,
        fontSize="10px")),
    lineColor=gainsboro),
  yAxis=list(
    labels=list(
      style=list(
        color=black,
        fontFamily = main_font, # font_axis_label
        fontWeight = regular_font_weight,
        fontSize="10px",
        margin = 50)),
    gridLineWidth=0, # removes vertical grid lines
    visible=TRUE, # makes axis line visible
    lineWidth=1,
    lineColor=gainsboro,
    min=0,
    tickAmount=6,
    tickWidth=1),
  legend = list(
    itemStyle = list(
      fontFamily = main_font, # font_axis_label
      fontWeight = regular_font_weight,
      color = black,
      fontSize = '12px'),
    itemHoverStyle = list(
      fontFamily = main_font, # font_table_text
      fontWeight = regular_font_weight,
      color = black),
    plotLines=list(color=gainsboro)))
  
#   # create boxplot dataframe
# data<-data_to_boxplot(df,variable=stop_duration_capped,group_var=bipoc, color="#3A207D")

# create caption 

timedot<-"<b style='font-size:10px;'>Each dot is a person stopped.</b>"

sourcenote<-"<br>Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made in 2022 that resulted in citation for infraction, warning, or no action."

racenote <- "Race is based on officer perception. People of Color includes all individuals perceived as non-White by officers."

caption_text <- paste("<br>", timedot, "<br>", sourcenote, methodnote, racenote)
```

```{r, echo=FALSE}

jitter_chart <- highchart() %>%
  hc_chart(inverted = TRUE) %>%
  hc_add_series(
    data = df,
    type = "scatter", 
    hcaes(x = bipoc, y = stop_duration_capped, group = bipoc),
    tooltip = list(headerFormat="", pointFormat = "{point.stop_duration_capped:.0f} minutes spent on a person perceived as {point.bipoc_label}"),
    color=paste0(meteorite)) %>%
  hc_legend(enabled = FALSE) %>%
  hc_plotOptions(
    scatter = list(
      marker = list(
        radius = 3,
        symbol = "circle",
        lineWidth = .2),
      jitter = list(x = .345, y = 0))) %>%
  hc_xAxis(type="category") %>%
  hc_yAxis(min=0, max=120, 
           title = list(text = "Time Spent on Stop (minutes)"))%>%
  hc_title(text = "Fresno PD Spends More Time on Traffic Stops Involving People of Color") %>%
  hc_caption(text=caption_text)%>%
  hc_subtitle(text = "Officer time spent on each person they stopped and gave a citation or warning or took no action.")%>%
  hc_add_theme(cc_theme) %>%
  hc_exporting(
      enabled = TRUE,
      sourceWidth=900,
      sourceHeight=600,
      chartOptions=list(
        plotOptions=list(
          series=list(
            dataLabels=list(
              enabled=TRUE,
              format=list(pointFormat="{point.stop_duration_capped:.0f} minutes spent on a person perceived as {point.bipoc_label}"))))),
      filename = paste0("Officer time spent stopping persons to cite an infraction and/or give a warning or take no action.","_Catalyst California, catalystcalifornia.org, 2024."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV'))))

jitter_chart

```

```{r, include=FALSE}
# # stop_result_list is not an actual list - need to convert and then can create  
# # column that checks if elements in that list are not in our target list 
# df_qa <- ois_traffic_race %>%
#   filter(stop_result_list == "citation for infraction") 
# 
# cor.test(df_qa$bipoc_flag, df_qa$stop_duration_capped)
# # significantly correlated, p-value = 0.00402
# # 95 percent confidence interval:
# #  0.01443254 0.07598923
# 
# jitter_chart2 <- highchart() %>%
#   hc_chart(inverted = TRUE) %>%
#   hc_add_series(
#     data = df_qa,
#     type = "scatter", 
#     hcaes(x = bipoc, y = stop_duration_capped, group = bipoc),
#     tooltip = list(headerFormat="", pointFormat = "{point.stop_duration_capped:.0f} minutes spent on a person perceived as {point.bipoc_label}"),
#     color=paste0(meteorite)) %>%
#   hc_legend(enabled = FALSE) %>%
#   hc_plotOptions(
#     scatter = list(
#       marker = list(
#         radius = 3,
#         symbol = "circle",
#         lineWidth = .2),
#       jitter = list(x = .345, y = 0))) %>%
#   hc_xAxis(type="category") %>%
#   hc_yAxis(min=0, max=120, 
#            title = list(text = "Time Spent on Stop (minutes)"))%>%
#   hc_title(text = "Fresno PD Spends More Time on Traffic Stops Involving People of Color") %>%
#   hc_caption(text=caption_text)%>%
#   hc_subtitle(text = "Officer time spent stopping persons to cite an infraction and/or give a warning or take no action.")%>%
#   hc_add_theme(cc_theme) %>%
#   hc_exporting(
#       enabled = TRUE,
#       sourceWidth=900,
#       sourceHeight=600,
#       chartOptions=list(
#         plotOptions=list(
#           series=list(
#             dataLabels=list(
#               enabled=TRUE,
#               format=list(pointFormat="{point.stop_duration_capped:.0f} minutes spent on a person perceived as {point.bipoc_label}"))))),
#       filename = paste0("Officer time spent stopping persons to cite an infraction and/or give a warning or take no action.","_Catalyst California, catalystcalifornia.org, 2024."),
#       buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
#                                                      'downloadXLS', 'downloadCSV'))))
# 
# jitter_chart2

```

```{r alternate-visual, include = FALSE}
# sum_df<-summary%>%select(race,min_time,,q25_time,median_time,q75_time,q95_time)%>%
#   pivot_longer(!race,names_to="measure", values_to="time")%>%
#   filter(!race %in% c('nh_aian','nh_multiracial','nh_nhpi','White','BIPOC'))%>%
#   mutate(race_label = case_when(
#     race == 'latinx' ~ "Latinx",
#     race =='nh_white' ~ 'White',
#     race =='nh_black' ~ 'Black',
#     race == 'nh_asian' ~ 'Asian',
#     race == 'nh_sswana' ~ 'SWANA/SA',
#     .default = as.character(race)),
#     measure=case_when(measure=='min_time' ~ 'Minimum Time',
#                       measure=='q25_time' ~ '25% of Stops',
#                       measure=='median_time' ~ '50% of Stops',
#                       measure=='q75_time' ~ '75% of Stops',
#                       measure=='q95_time' ~ '95% of Stops',
#                       .default = as.character(measure)))
# 
# sum_df$race_label <- factor(x=sum_df$race_label, levels = c('Asian','Black', 'Latinx', 'White', 'SWANA/SA')) # factor levels to order plot by
# sum_df$measure <- factor(x=sum_df$measure, levels = c('Minimum Time', '25% of Stops', '50% of Stops', '75% of Stops', '95% of Stops', 'Maximum Time'))
# 
# sum_chart<-highchart() %>%
#   hc_chart(inverted = TRUE) %>%
#    hc_xAxis(type = "category") %>%
#    hc_add_series(
#     data = sum_df,
#     type = "scatter",
#     hcaes(x = race_label, y = time, group = measure),
#     tooltip = list(headerFormat="", pointFormat = "{point.time:.0f} minutes spent on {point.measure} of people perceived as {point.race_label}")
#   ) %>%
#   hc_plotOptions(scatter = list(
#     marker = list(
#       radius = 5,
#       symbol = "circle",
#       lineWidth = .5
#     )
#   ))  %>%
#   hc_colors(list("#372278", "#5F3B63","#A8683C", "#D58424", "#FF9900"))%>%
#   hc_title(text = "Fresno PD Often Spends More Time on Traffic Stops Involving People Perceived as Black or Asian") %>%
#   hc_caption(text=caption_text)%>%
#     hc_subtitle(text = "Range of time spent on traffic stops resulting in a citation for infraction, warning, or no action by race")%>%
#   hc_add_theme(cc_theme)
# 
# 
# sum_chart
# 
# 
# bipoc_sum_df<-summary%>%select(race,min_time,,q25_time,median_time,q75_time,q95_time,max_time)%>%
#   pivot_longer(!race,names_to="measure", values_to="time")%>%
#   filter(race %in% c('White','BIPOC'))%>%
#   mutate(race_label = case_when(
#     race == 'BIPOC' ~ "People of Color",
#     .default = as.character(race)),
#     measure=case_when(measure=='min_time' ~ 'Minimum Time',
#                       measure=='q25_time' ~ '25% of Stops',
#                       measure=='median_time' ~ '50% of Stops',
#                       measure=='q75_time' ~ '75% of Stops',
#                       measure=='q95_time' ~ '95% of Stops',
#                       measure=='max_time' ~ 'Maximum Time',
#                       .default = as.character(measure)))
# 
# bipoc_sum_df$race_label <- factor(x=bipoc_sum_df$race_label, levels = c('People of Color','White')) # factor levels to order plot by
# bipoc_sum_df$measure <- factor(x=bipoc_sum_df$measure, levels = c('Minimum Time', '25% of Stops', '50% of Stops', '75% of Stops', '95% of Stops', 'Maximum Time'))
# 
# bipoc_sum_chart<-highchart() %>%
#   hc_chart(inverted = TRUE) %>%
#    hc_xAxis(type = "category") %>%
#    hc_add_series(
#     data = bipoc_sum_df,
#     type = "scatter",
#     hcaes(x = "race_label", y = "time", group = "measure"),
#     tooltip = list(headerFormat="", pointFormat = "{point.time:.0f} minutes spent on {point.measure} of people perceived as {point.race_label}")
#   ) %>%
#   hc_plotOptions(scatter = list(
#     marker = list(
#       radius = 5,
#       symbol = "circle",
#       lineWidth = .5
#     )
#   ))  %>%
#   hc_colors(list("#372278", "#5F3B63","#A8683C", "#D58424", "#FF9900", "#E76C30"))%>%
#   hc_title(text = "Fresno PD Often Spends More Time on Traffic Stops Involving People Perceived as Black or Asian") %>%
#   hc_caption(text=caption_text)%>%
#     hc_subtitle(text = "Range of time spent on traffic stops resulting in a citation for infraction, warning, or no action by race")%>%
#   hc_add_theme(cc_theme)
# 
# bipoc_sum_chart


# # try relative freq histogram
# hist_a <- hist(df$stop_duration_capped[df$bipoc == "White"], breaks = 100, plot = FALSE)
# hist_a$counts <- hist_a$counts/sum(hist_a$counts)
# hist_b <- hist(df$stop_duration_capped[df$bipoc == "People of Color"], breaks = 100, plot = FALSE)
# hist_b$counts <- hist_b$counts/sum(hist_b$counts)
# 
# # Create data for highcharter
# series_a <- data.frame(
#   x = hist_a$mids,
#   y = hist_a$counts
# )
# 
# series_b <- data.frame(
#   x = hist_b$mids,
#   y = hist_b$counts
# )
# 
# # Create the plot
# highchart() %>%
#   hc_chart(type = "column") %>%  # Use column instead of histogram
#   hc_add_series(
#     data = list_parse(series_a),  # Convert data to highcharter format
#     name = "White",
#     color = "#4682B480"  # Steel blue with 50% opacity
#   ) %>%
#   hc_add_series(
#     data = list_parse(series_b),
#     name = "People of Color",
#     color = "#CD5C5C80"  # Indian red with 50% opacity
#   ) %>%
#   hc_title(text = "Distribution by Group") %>%
#   hc_xAxis(title = list(text = "Value"), max=60) %>%
#   hc_yAxis(title = list(text = "Frequency")) %>%
#   hc_plotOptions(
#     column = list(
#       grouping = FALSE,  # Allows overlapping
#       pointPadding = 0,
#       groupPadding = 0,
#       borderWidth = 0
#     )
#   ) %>%
#   hc_tooltip(
#     shared = TRUE,
#     headerFormat = "<b>Bin center: {point.x:.2f}</b><br/>",
#     pointFormat = "{series.name}: {point.y}"
#   )

```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>