---
title: ""
output:
  html_document:
    includes:
      in_header: "../header.html"
---

```{r, include=FALSE}
# Check if document is being run as a child, if yes don't apply styling again
is_child <- !is.null(knitr::opts_knit$get("parent.frame"))
if (is_child) {
  knitr::opts_chunk$set(include = FALSE)
}
```

```{r, include=FALSE}

# set up -----------------------------
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
# remotes::install_github("catalystcalifornia/rdaCharts", upgrade="never")
library(rdaCharts)
library(htmltools) 

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull and clean analysis tables for visualizing ----

df_p<-dbGetQuery(con, "SELECT * FROM report_traffic_detained")

# filter groups being visualized and select rate and counts to be visualized
df<-df_p%>%filter(race %in% c("nh_white","latinx","nh_asian","nh_aian","nh_nhpi","nh_multiracial","nh_black","nh_sswana"))%>%
    filter(gender_race_traffic_total>=5) %>% # only include groups where at least 5 people were stopped in traffic stops
  select(race,gender,detained_count,detained_total,detained_total_rate)%>%
  arrange(-detained_total_rate)%>%
  filter(detained_total_rate>0)%>%
  mutate(detained_total_rate=detained_total_rate*100)

# create race label
df<-df%>%mutate(race_label = case_when(
    race == 'latinx' ~ "Latinx", 
    race =='nh_white' ~ 'White',
    race =='nh_black' ~ 'Black',
    race == 'nh_asian' ~ 'Asian',
   race == 'nh_multiracial' ~ 'Multiracial',
    race == 'nh_aian' ~ 'AIAN',
    race == 'nh_nhpi' ~ 'NHPI',
    race == 'nh_sswana' ~ 'SWANA/SA', 
    TRUE ~ as.character(race)),
   label=paste0(race_label," ",gender))

# visualize--------------------------

# create caption 

sourcenote<-"Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis covers all officer-initiated traffic stops in 2022 that included an officer detaining a person. Genders are based on identification by officers. According to the data source, officers did not report detaining people perceived as transgender or gender nonconforming. Officers did not report detaining people perceived as American Indian/Alaska Native or Native Hawaiian/Pacific Islander alone."

racenote <- "Race/ethnicity: SWANA/SA=Southwest Asian (Middle Eastern)/North African/South Asian."

caption_text <- paste(sourcenote, methodnote,racenote)


# create tooltip text

tooltip_text <- "Fresno PD detained {point.detained_total} people during officer-initiated traffic stops. <b>{point.detained_total_rate:.1f}%</b> of these people were perceived as <b>{point.label}s</b> by officers."

# Visualizing as table --------------------------

chart_race<-rdaBar(
  df,
  "label",
  "detained_total_rate",
  theme="theme_fbhc",
  title="Fresno PD Disproportionately Detains Latinx Males During Traffic Stops",
  subtitle="Percent of people detained during officer-initiated traffic stops by perceived race and gender",
  tooltip_text=tooltip_text,
  caption=caption_text,
  export_data_label=list(pointFormat='{point.detained_total_rate:.1f}%'))

```

```{r, echo=FALSE}

chart_race

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>