---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

# set up -----------------------------

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")

# library(devtools)
# remotes::install_github("catalystcalifornia/rdaCharts") 
library(rdaCharts)
library(stringr)
library(htmltools) 
library(htmlwidgets)
library(gtExtras)
library(gt)
#connect to postgres

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull analysis table for visualizing


df<-dbGetQuery(con, "SELECT * FROM report_traffic_result_race")%>%
  mutate(stop_result_simple = str_to_title(stop_result_simple))%>%
  mutate(race_label=ifelse(race %in% "latinx", "Latinx",
                           ifelse(race %in% "nh_aian", "AIAN NH",
                                  ifelse(race %in% "nh_black", "Black",
                                         ifelse(race %in% "nh_multiracial", "Multiracial",
                                                ifelse(race %in% "nh_nhpi", "NHPI NH",
                                                       ifelse(race %in% "nh_sswana", "SSWANA NH",
                                                              ifelse(race %in% "nh_white", "White",
                                                              ifelse(race %in% "aian_aoic", "AIAN",
                                                                     ifelse(race %in% "nhpi_aoic", "NHPI",
                                                                            ifelse(race %in% "sswana_aoic","SWANA/SA",
                                                                                   ifelse(race %in% 'nh_asian', "Asian", race))))))))))))%>%
  filter(race!="nh_sswana")

# filter dataframes with different denominators to visualize and make decision on which embed to use for report

df_race<-df%>%
  filter(denom=="traffic_stop_race")%>%
  filter(race!="nh_nhpi" & race != "nh_aian")

df_result<-df%>%
  filter(denom=="traffic_result")%>%
  group_by(race)%>%
  arrange(-count) #want to look by count not rates

df_pop<-df%>%
  filter(denom=="population")

```

```{r, include=FALSE}

# Set up embed info------------------

# create caption 

sourcenote<-"Catalyst California calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated stops made by officers in 2022."

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption_text <- paste("<br>", racenote, sourcenote, methodnote)

# create tooltip text

tooltip_text <- "Out of 100 people Fresno PD stopped and perceived as <b>{point.race_label}</b> in officer-initiated traffic stops,  <b>{point.rate:.1f}%</b> of them were given a <b>{point.stop_result_simple}</b> as a result of the stop, or a total of <b>{point.count:.1f}</b> people."


# Visualize the "traffic_race" denominator but as a table------------------------


# select just columns of interest, specify header and footer
table_race<-df_race%>%
  filter(!grepl("nh_aian|nh_sswana|nh_nhpi", race))%>%
group_by(race_label)%>%
  slice(1:3)%>%
  # ungroup()%>%
    mutate(stop_result_simple = str_to_title(stop_result_simple))%>%
  mutate("Count (%)"=paste0(count," (",round(rate,0),"%)"),
         "Race"=race_label,
         " "=rate,
         "Stop Result"=stop_result_simple)%>%
    select("Race", "Stop Result","Count (%)"," ")%>%
  gt()%>%
  # question
  tab_header(title=glue::glue("Fresno PD Makes Traffic Stops for Reasons That Do Not Improve Safety"),
             subtitle="Most common traffic citation results by traffic stop type")%>%
  # any data notes in footer
  tab_footnote(footnote=html(caption_text),placement="left")%>%
  gt_plt_bar_pct(column=" ", scaled=FALSE, fill="#3A207D",background="transparent")%>%
  # if needed modify column widths here
  cols_width(1~px(175),2~px(160),
             3~px(250))%>%
  opt_align_table_header("left")%>%
  opt_table_font(font=c(google_font(name="Inter"),locations=NULL,default_fonts()))%>%
  tab_options(table.background.color="#FBFBFB",
    column_labels.background.color = "transparent",
    table.font.size = px(12),
    column_labels.font.size = px(12),
    heading.align = "left",
    table.font.names = "Inter",
    heading.title.font.size = px(20),
    heading.subtitle.font.size = px(13),
    heading.border.bottom.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "#DEDEDE",
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    data_row.padding = px(3),
    footnotes.font.size = px(10),
    footnotes.border.bottom.color = "transparent",
    table.align='center')%>%
  tab_style(style=
            cell_borders(sides=c("top","bottom"),color="#DEDEDE",style="solid",weight=px(1)),locations=cells_body())%>%
   tab_style(style=
            cell_text(font=c(google_font(name="Inter"),default_fonts()),weight=900, color="black"),locations=cells_title())

# table_race

# visualize the "traffic_race" denom with graph function--------------------------

df_race<-df_race%>%
  group_by(race_label)%>%
  slice(1:3)

chart_race<-rdaGroupedBar(
  df_race,
  "race_label",
  "rate",
  "stop_result_simple",
  title = "The Majority of Traffic Stops made by Fresno PD Result in a Citation",
  subtitle = "Percent of officer-initiated traffic stops by stop result and perceived race",
  tooltip_text = tooltip_text,
  caption = caption_text,
  export_data_label = list(pointFormat='{point.rate:.1f}%') 
)

```

```{r, include=FALSE}

# Visualize the "traffic_result" denominator but as a table------------------------


# select just columns of interest, specify header and footer
table_result<-df_result%>%
  filter(!grepl("nh_aian|nh_sswana|nh_nhpi", race))%>%
group_by(race_label)%>%
  slice(1:3)%>%
  # ungroup()%>%
    mutate(stop_result_simple = str_to_title(stop_result_simple))%>%
  mutate("Count (%)"=paste0(count," (",round(rate,0),"%)"),
         "Race"=race_label,
         " "=rate,
         "Stop Result"=stop_result_simple)%>%
    select("Race", "Stop Result","Count (%)"," ")%>%
  gt()%>%
  # question
  tab_header(title=glue::glue("Fresno PD Makes Traffic Stops for Reasons That Do Not Improve Safety"),
             subtitle="Most common traffic citation results by traffic stop type")%>%
  # any data notes in footer
  tab_footnote(footnote=html(caption_text),placement="left")%>%
  gt_plt_bar_pct(column=" ", scaled=FALSE, fill="#3A207D",background="transparent")%>%
  # if needed modify column widths here
  cols_width(1~px(175),2~px(160),
             3~px(250))%>%
  opt_align_table_header("left")%>%
  opt_table_font(font=c(google_font(name="Inter"),locations=NULL,default_fonts()))%>%
  tab_options(table.background.color="#FBFBFB",
    column_labels.background.color = "transparent",
    table.font.size = px(12),
    column_labels.font.size = px(12),
    heading.align = "left",
    table.font.names = "Inter",
    heading.title.font.size = px(20),
    heading.subtitle.font.size = px(13),
    heading.border.bottom.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "#DEDEDE",
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    data_row.padding = px(3),
    footnotes.font.size = px(10),
    footnotes.border.bottom.color = "transparent",
    table.align='center')%>%
  tab_style(style=
            cell_borders(sides=c("top","bottom"),color="#DEDEDE",style="solid",weight=px(1)),locations=cells_body())%>%
   tab_style(style=
            cell_text(font=c(google_font(name="Inter"),default_fonts()),weight=900, color="black"),locations=cells_title())

# table_result

# Visualize result denom with chart function ----------------------------

chart_result<-rdaStackedBar(
  df_result,
  "race_label",
  "rate",
  "stop_result_simple",
  title = "The Majority of Traffic Stops made by Fresno PD Result in a Citation",
  subtitle = "Percent of officer-initiated traffic stops by stop result",
  tooltip_text = tooltip_text,
  caption = caption_text,
  export_data_label = list(pointFormat='{point.rate:.1f}%') 
)


```

```{r, echo=FALSE}

chart_race

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>