---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}
# set up -----------------------------
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
# library(devtools)
 # remotes::install_github("catalystcalifornia/rdaCharts")
library(rdaCharts)
# library(htmltools) 

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("eci_fresno_ripa")

# pull and clean analysis tables for visualizing ----
df_p<-dbGetQuery(con, "SELECT * FROM report_timespent_reason")

```


```{r, include=FALSE}
# filter columns of interest and recode stop reason for simplicity
df <- df_p %>%
  select(stop_reason,hours_count,hours_total,hours_rate) %>%
  mutate(reason_label = case_when(
    stop_reason == 'Consensual encounter resulting in search' ~ "Consensual encounter and search", 
    stop_reason =='Parole/probation/PRCS/ mandatory supervision' ~ 'Other reasons',
    stop_reason =='Knowledge of outstanding arrest/wanted person' ~ 'Knowledge of outstanding arrest',
    stop_reason == 'Two or More reasons' ~ 'Other reasons',
    .default = as.character(stop_reason)),
    hours_rate=hours_rate*100) %>%
  group_by(reason_label,hours_total) %>%
  summarise(hours_rate=sum(hours_rate),
            hours_count=sum(hours_count)) %>%
  arrange(-hours_rate)

```

```{r, include=FALSE}
# visualize--------------------------
## COLORS ##
papaya <- "#F25922"
peridot <- "#CEEA01"
lavender <- "#CEC4E2"
meteorite <- "#3A207D"
ccblue <- "#0860BC"

black <- "#000000"
alabaster<-"#FBFBFB"
gainsboro <- "#DEDEDE"

 ## FONTS ##
main_font <- "Inter"
regular_font_weight <- 400
black_font_weight <- 800
semi_bold_font_weight <- 600


##### highchart theme #####
cc_theme <- hc_theme(
  colors = c(meteorite, lavender, papaya, peridot),
  chart = list(
    backgroundColor = alabaster,
    style = list(
      fontFamily = main_font, # font_subtitle
      color=alabaster)),
  title = list(widthAdjust = -50,
               style = list(
                 color = black,
                 fontFamily = main_font, # font_title
                 fontWeight = black_font_weight,
                 textAlign="left",
                 fontSize='21px'),
                 align = "left"),
  subtitle = list(
    style = list(
      color = black,
      fontFamily = main_font, # font_subtitle
      fontWeight = regular_font_weight,
      fontSize='14px'),
      align='left'),
  caption = list(
    style = list(
      color = black,
      fontFamily = main_font, # font_caption
      fontWeight = regular_font_weight,
      fontSize = "10px",
      textAlign = "left",
      width = 50),
    useHTML = TRUE,
    floating = FALSE),
  xAxis=list(
    labels=list(
      style=list(
        color=black,
        fontFamily = main_font, # font_x_label
        fontWeight = semi_bold_font_weight,
        width=120,  #argument to modify the width of the labels
        min=0,
        fontSize="10px")),
    lineColor=gainsboro),
  yAxis=list(
    labels=list(
      style=list(
        color=black,
        fontFamily = main_font, # font_axis_label
        fontWeight = regular_font_weight,
        fontSize="10px",
        margin = 50)),
    gridLineWidth=0, # removes vertical grid lines
    visible=TRUE, # makes axis line visible
    lineWidth=1,
    lineColor=gainsboro,
    min=0,
    tickAmount=6,
    tickWidth=1),
  legend = list(
    itemStyle = list(
      fontFamily = main_font, # font_axis_label
      fontWeight = regular_font_weight,
      color = black,
      fontSize = '12px'),
    itemHoverStyle = list(
      fontFamily = main_font, # font_table_text
      fontWeight = regular_font_weight,
      color = black),
    plotLines=list(color=gainsboro)))

# create caption 
sourcenote<-"Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made by officers in 2022. Other reasons include stops for probation or parole and stops made for two or more reasons."

caption_text <- paste("<br>", sourcenote, methodnote)

# create tooltip text
tooltip_text <- "Out of all of time spent on officer-initiated stops, Fresno PD spent <b>{point.hours_rate:.1f}%</b> of their time on stops for <b>{point.reason_label}</b>. "

```

```{r, echo=FALSE}
# Visualizing as bar chart --------------------------
# chart <- rdaBar(
#   df,
#   "reason_label",
#   "hours_rate",
#   title="Fresno PD Spends Most of Their Patrol Time on Traffic Stops",
#   subtitle="Percent of time spent on officer-initiated stops by stop reason",
#   tooltip_text=tooltip_text,
#   caption=caption_text,
#   export_data_label=list(pointFormat='{point.hours_rate:.1f}%'))
# 
# chart

```

```{r, echo=FALSE}
# Visualizing as stacked bar --------------------------
df$x <- "x"

reason_levels <- c("Traffic violation", "Reasonable suspicion", "Knowledge of outstanding arrest",
                   "Consensual encounter and search", "Other reasons")
colors_stacked <- c("#E9E9E9", "#D6D6D6", "#BABABA", "#9B9A9A", "#362178")

df$reason_label <- factor(x=df$reason_label, 
                          levels = rev(reason_levels)) # factor levels to order plot by

chart <-highchart() %>%
  hc_chart(inverted = TRUE) %>%
  hc_add_series(data=df,
                type="column", 
                hcaes(x=x, y=hours_rate, group=reason_label),
                tooltip = list(headerFormat="", pointFormat = tooltip_text),
                color=colors_stacked) %>%
  hc_xAxis(labels = list(enabled=FALSE),
           visible=FALSE) %>%
  hc_yAxis(min=0, max=100, labels = list(format = "{value}%")) %>%
  hc_legend(reversed=TRUE) %>%
  hc_plotOptions(series=list(stacking='normal')) %>%
  hc_title(useHTML=TRUE,
           text = paste("Fresno PD Spends Nearly ", "<span style='color:#362178;'>98%</span>", "of Their Patrol Time on Traffic Stops")) %>%
  hc_subtitle(text = "Percent of time spent on officer-initiated stops by stop reason") %>%
  hc_caption(text=caption_text)%>%
  hc_add_theme(cc_theme)  %>%
  hc_exporting(
      enabled = TRUE,
      sourceWidth=900,
      sourceHeight=600,
      chartOptions=list(
        plotOptions=list(
          series=list(
            dataLabels=list(
              enabled=TRUE,
              format=list(pointFormat='{point.hours_rate:.1f}%'))))),
      filename = paste0("Percent of time spent on officer-initiated stops by stop reason","_Catalyst California, catalystcalifornia.org, 2024."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV'))))

chart

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>