---
title: ""
output:
  html_document:
    includes:
      in_header: "../header.html"
---

```{r, include=FALSE}
# Check if document is being run as a child, if yes don't apply styling again
is_child <- !is.null(knitr::opts_knit$get("parent.frame"))
if (is_child) {
  knitr::opts_chunk$set(include = FALSE)
}
```

```{r load, include=FALSE}

# set up -----------------------------
library(RPostgreSQL)
library(dplyr)
library(highcharter)
# remotes::install_github("catalystcalifornia/rdaCharts", upgrade="never") 
library(rdaCharts)
library(purrr) # facet charts
library(htmltools)

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("eci_fresno_ripa")

# pull analysis table for visualizing
traffic_reason_race <- dbGetQuery(con, "SELECT * FROM report_traffic_reason_race")

dbDisconnect(con)
```

```{r prep-data, include=FALSE}
df <- traffic_reason_race %>%
  filter(race!="nh_sswana") %>% # don't need this will use sswana_aoic which is the same
  mutate(race_label = 
           case_when(
             race == 'latinx' ~ "Latinx",
             race =='nh_white' ~ 'White',
             race =='nh_black' ~ 'Black',
             race == 'nh_asian' ~ 'Asian',
             race == 'nh_multiracial' ~ 'Multiracial',
             race == 'aian_aoic' ~ 'AIAN',
             race == 'nh_aian' ~ 'AIAN NH',
             race == 'nhpi_aoic' ~ 'NHPI',
             race == 'nh_nhpi' ~ 'NHPI NH',
             race == 'sswana_aoic' ~ 'SWANA/SA',
             .default = as.character(race)),
         statute_literal_25 = 
           case_when(
             statute_literal_25 == 'UNSAFE SPEED:PREVAIL COND' ~ "Unsafe Speed while Driving Vehicle",
             statute_literal_25 =='NO REG:VEH/TRAILER/ETC' ~ 'No Vehicle Registration',
             statute_literal_25 =='OPR VEH:WINDOW OBSTRUCTED' ~ 'Obstructed Window',
             statute_literal_25 == 'FAIL STOP LINE/ETC AT RED' ~ 'Failure to Stop at Red Light',
             .default = as.character(statute_literal_25)))


# split separate dfs for each denominator option-----
df_race <- df %>%
  filter(denom=="traffic_stop_race" & count >= 5) # I think this denominator is the best one for visualizing

# Combine the two 'using cell phone with no handheld device' citations into one -----
summed <- df_race %>%
  select(race, denom, statute_literal_25, total, count, race_label) %>%
  filter(statute_literal_25 %in% c("USE CELLPH W/DRIV W/O HFD", "NO HND HLD DEVICE W/DRIVE")) %>%
  group_by(race, denom) %>%
  summarise(statute_literal_25= "Use of Cellphone with No Handheld Device",
            total=total,
            count = sum(count),
            rate=count/total*100,
            race_label=race_label) %>%
  slice(1) %>%
  ungroup()

# Append these summed rows to the original data frame
df_combined <- rbind(df_race, summed)

# rearrange df and remove the previous separate cell phone citations
df_final <- df_combined %>%
  filter(grepl("Obstructed Window|No Vehicle Registration", statute_literal_25)) %>%
  arrange(race, -rate)

```

```{r prep-visual, include=FALSE}
# create title
title_text <- "Officers Are Biased in When They Stop People For Reasons Not Related to Public Safety"

# create caption 
sourcenote <- "Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024."

methodnote <- "Analysis covers all officer-initiated traffic stops in 2022. Groups with <10 stops (NHPI, AIAN) were excluded from the chart."

racenote <- "Race/ethnicity: SWANA/SA=Southwest Asian (Middle Eastern)/North African/South Asian."

caption_text <- paste(sourcenote, methodnote,racenote)

# create tooltip text
tooltip_text <- "Out of all the people Fresno PD stopped for traffic reasons and perceived as <b>{point.race_label}</b>, <b>{point.rate:.1f}%</b> of those people were stopped for <b>{point.statute_literal_25}</b>, or a total of <b>{point.count:.f}</b> people."

# get rdaCharts theme for custom chart
data(theme_options)
list2env(theme_options, envir = .GlobalEnv)

```

```{r create-visual, echo=FALSE, include=FALSE, message=FALSE}
# Facet charts
list_of_plots <- map(unique(df_final$statute_literal_25), function(x) {
  filtered_data <- df_final %>%
    filter(statute_literal_25 == x) %>%
    arrange(desc(rate)) %>%  # Sort by descending y-values
    mutate(bar_color = ifelse(race_label == "White", "#053451","#FDB913"))  # Custom color for "White"
  
  if (nrow(filtered_data) == 0) {
    return(NULL)  # Skip this group if there are no rows
  }
  
  highchart() %>%
    hc_add_series(filtered_data, 
                  "bar", 
                  hcaes(x = race_label, 
                        y = rate, 
                        color=bar_color),
                  showInLegend = FALSE) %>%
    hc_plotOptions(column = list(stacking = "normal")) %>%
    hc_add_theme(theme_fbhc) %>%
    hc_subtitle(text = paste0("Percent of traffic stops made for  ", x,
                              " reason out of all traffic stops by race"),
                style = list(
                  fontSize = "16px",
                  lineHeight = "22px")) %>%
    hc_yAxis(title = list(text = "Percent (%)",
                          style = list(
                            color = "#0A0A0A"
                          )),
             labels= list(style = list(
                            fontSize = "12px",
                            color = "#0A0A0A"),
                          overflow = "justify"))%>%
    hc_xAxis(title = list(text = ""),
             labels= list(position="bottom",
                          style = list(
                            fontSize = "12px"),
                          overflow = "justify"),
             type = "category")%>%
    hc_tooltip(headerFormat='', # removes series label from top of tooltip
               pointFormat = tooltip_text,
               outside = TRUE,
               useHTML=TRUE,
               style = list(fontSize = "14px")) %>%
    hc_chart(
      height = 600,
      reflow = TRUE,
      marginLeft = 80,
      marginRight = 80) %>%
  hc_exporting(
      enabled = TRUE,
      sourceWidth=900,
      sourceHeight=600,
      chartOptions=list(
        title = list(
          text = title_text,
          style = list(
            color = "#0A0A0A",
            fontSize = "21px",
            lineHeight = "28px",
            fontFamily = "Montserrat",
        fontWeight = "800"),
        align = "left"),
        caption = list(
          text = caption_text,
          style = list(
            fontSize = "12px",
            lineHeight = "18px"),
          align = "left",
          y = 15),
    plotOptions=list(
      series=list(
        dataLabels=list(
          enabled=TRUE,
          format = '{point.rate:.1f}',
          style = list(fontSize = "14px"))))),
      filename = paste0("Percent of traffic stops made for  ", x, " reason out of all traffic stops by race","_Catalyst California, catalystcalifornia.org, ", format(Sys.Date(), "%Y"), "."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV'))))
})

```

```{r, echo=FALSE}
# Display chart
  
browsable(
  tagList(
    # Main title
    tags$text(title_text, 
              class="highcharts-title",
              style=css(
                color="#0A0A0A",
                font.size="21px",
                line.height="28px",
                font.family="Montserrat",
                font.weight="800",
                text.align="left",
                fill="#0A0A0A")),
    # Faceted charts
    list_of_plots %>% 
      hw_grid(rowheight = 450)))

```
<span class="highcharts-caption" data-z-index="4" style="font-family: open-sans; font-size: 12px; white-space: normal; margin-left: 0px; margin-top: 0px; left: 10px; top: 513px; color: rgb(10, 10, 10); font-weight: 400; text-align: left; line-height: 18px; width: 100%; display: block;">Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024.  Analysis covers all officer-initiated traffic stops in 2022. Groups with <5 stops (NHPI, AIAN) were excluded from the chart. Race/ethnicity: SWANA/SA=Southwest Asian (Middle Eastern)/North African/South Asian.</span>

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>