---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

# set up -----------------------------

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")

source("W:\\RDA Team\\Packages\\rdaCharts\\HK\\R\\rdaBubblepop.R") # sourcing one of the visual files so I can get color codes

# library(devtools)
#  remotes::install_github("catalystcalifornia/rdaCharts") 
library(rdaCharts)
library(stringr)
library(htmltools) 
library(htmlwidgets)
# remotes::install_github("jthomasmock/gtExtras")
library(gtExtras)
library(gt)
library(extrafont)
library(usethis)

#connect to postgres

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull analysis tables for visualizing

df<-dbGetQuery(con, "SELECT * FROM report_citation_traffic_type_stop")%>%
    mutate(statute_literal_25 = str_to_title(statute_literal_25)) # convert text for offense to be title case
  
# Manually combine the two 'cell phone without handheld' offenses into one 

sum_values <- df %>%
  group_by(traffic_violation_type)%>%
  filter(statute_literal_25 %in% c("Use Cellph W/Driv W/O Hfd", "No Hnd Hld Device W/Drive")) %>%
  summarise(statute_literal_25="Using Cell Phone Without Handheld Device While Driving",
    total=ifelse(traffic_violation_type == "Moving", total, NA),
            count_sum = sum(count),
            rate=count_sum/total*100)%>%
  ungroup()%>%
  slice(1)%>%
  rename("count"="count_sum")


# Add new combined row to df and remove thse two separate handheld offenses 

df <- rbind(df, sum_values)

df<-df%>%
  filter(!grepl("Use Cellph W/Driv W/O Hfd|No Hnd Hld Device W/Drive", statute_literal_25))%>%
  group_by(traffic_violation_type)%>%
  arrange(-rate)


# visualize--------------------------

# create caption 

sourcenote<-"Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made by officers in 2022."

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption_text <- paste("<br>", sourcenote, methodnote)


# Visualizing as table --------------------------


# select just columns of interest, specify header and footer
table<-df%>%
  # filter(!grepl("Moving", traffic_violation_type))%>% 
  group_by(traffic_violation_type)%>%
  slice(1:3)%>%
  mutate(statute_literal_25=ifelse(statute_literal_25 %in% "Opr Veh:window Obstructed", "Obstructed Window",
                         ifelse(statute_literal_25 %in% "Drive W/O License", "Driving Without a License",
                                   ifelse(statute_literal_25 %in% "Fail Prove Fin Rsp:po Req", "Failure to Prove Financial Responsibility (i.e. Insurance)",
                                   ifelse(statute_literal_25 %in% "Display Lic Plates Wrong", "Incorrect License Plate Displayed",
                                          ifelse(statute_literal_25 %in% "No Reg:veh/Trailer/Etc", "No Vehicle Registration",
                                                 ifelse(statute_literal_25 %in% "Unlaw Dirct Drv Opr/Hwy", "Unlawful Direction of Driving on a Highway",
                                                        ifelse(statute_literal_25 %in% "Unsafe Speed:prevail Cond", "Operating Vehicle at Unsafe Speed",statute_literal_25))))))))%>%
  mutate("Count (%)"=paste0(count," (",round(rate,0),"%)"),
         " "=rate,
         "Traffic Violation Type"=traffic_violation_type,
         "Traffic Stop Citation Result"=statute_literal_25)%>%
    ungroup()%>%
    select("Traffic Violation Type", "Traffic Stop Citation Result","Count (%)"," ")%>%
  gt()%>%
  # question
  tab_header(title=glue::glue("At The End of a Stop, Fresno PD Cites People For Offenses That Do Not Require Police or Advance Public Safety"),
             subtitle="Most common traffic citation results by traffic stop type")%>%
  # any data notes in footer
  tab_footnote(footnote=html(caption_text),placement="left")%>%
  gt_plt_bar_pct(column=" ", scaled=FALSE, fill="#3A207D",background="transparent")%>%
  # if needed modify column widths here
  cols_width(1~px(175),2~px(160),
             3~px(250))%>%
  opt_align_table_header("left")%>%
  opt_table_font(font=c(google_font(name="Inter"),locations=NULL,default_fonts()))%>%
  tab_options(table.background.color="#FBFBFB",
    column_labels.background.color = "transparent",
    table.font.size = px(12),
    column_labels.font.size = px(12),
    heading.align = "left",
    table.font.names = "Inter",
    heading.title.font.size = px(20),
    heading.subtitle.font.size = px(13),
    heading.border.bottom.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "#DEDEDE",
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    data_row.padding = px(3),
    footnotes.font.size = px(10),
    footnotes.border.bottom.color = "transparent",
    table.align='center')%>%
  tab_style(style=
            cell_borders(sides=c("top","bottom"),color="#DEDEDE",style="solid",weight=px(1)),locations=cells_body())%>%
   tab_style(style=
            cell_text(font=c(google_font(name="Inter"),default_fonts()),weight=900, color="black"),locations=cells_title())


```

```{r, echo=FALSE}

table

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>