---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

# set up -----------------------------

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")

source("W:\\RDA Team\\Packages\\rdaCharts\\HK\\R\\rdaBubblepop.R") # sourcing one of the visual files so I can get color codes

# library(devtools)
#  remotes::install_github("catalystcalifornia/rdaCharts") 
library(rdaCharts)
library(stringr)
library(htmltools) 
library(htmlwidgets)
# remotes::install_github("jthomasmock/gtExtras")
library(gtExtras)
library(gt)
library(extrafont)
library(usethis)

#connect to postgres

source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull analysis tables for visualizing

df<-dbGetQuery(con, "SELECT * FROM report_traffic_result_citation_license_race")%>%
    mutate(statute_literal_25 = "Driving Without a License")%>% # convert text for offense to be title case
  mutate(race_label=ifelse(race %in% "latinx", "Latinx",
                           ifelse(race %in% "nh_aian", "AIAN NH",
                                  ifelse(race %in% "nh_black", "Black",
                                         ifelse(race %in% "nh_multiracial", "Multiracial",
                                                ifelse(race %in% "nh_nhpi", "NHPI NH",
                                                       ifelse(race %in% "nh_sswana", "SSWANA NH",
                                                              ifelse(race %in% "nh_white", "White",
                                                              ifelse(race %in% "aiain_aoic", "AIAN",
                                                                     ifelse(race %in% "nhpia_aoic", "NHPI",
                                                                            ifelse(race %in% "sswana_aoic","SWANA/SA",
                                                                                   ifelse(race %in% 'nh_asian', "Asian", race))))))))))))%>%
  filter(race!="nh_sswana")%>%
  arrange(-rate)

# split up the df by the denominator options

df_result<-df%>%
  filter(denom=="citation_result")

df_race<-df%>%
  filter(denom=="citation_race")

```

```{r, include=FALSE}

# visualize--------------------------

# create caption 

sourcenote<-"Catalyst California calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made by officers in 2022 that resulted in a citation for infraction."

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption_text <- paste("<br>", racenote, sourcenote, methodnote)

# create tooltip text

tooltip_text <- "Out of 100 citations Fresno PD gave to people perceived as <b>{point.race_label}</b>, <b>{point.rate:.1f}%</b> were for <b>{point.statute_literal_25}</b>, or a total of <b>{point.count:.1f}</b> people cited."


# Run bubblechart function

  ## COLORS ##
  papaya <- "#F25922"
  peridot <- "#CEEA01"
  lavender <- "#CEC4E2"
  meteorite <- "#3A207D"
  ccblue <- "#0860BC"

  black <- "#000000"
  alabaster<-"#FBFBFB"
  gainsboro <- "#DEDEDE"

  # add custom ordering on stacked bar
  
  
# add factors for sorting
df_result <- within(df_result, race_label <- factor(race_label, levels=c("White","SWANA/SA", "Asian","Black", "Latinx")))


chart<-rdaStackedBar(
  df_result,
 statute_literal_25,
  "rate",
  race_label,
 bar_colors=list( gainsboro, "#949494", lavender, "#8E7ACA", "#362178"),
  title = "Fresno PD Is Twice as Likely to Cite Perceived Latinx Drivers for Driving Without a License Compared to Perceived White Drivers",
  subtitle = "Rate of traffic stops that result in a citation for driving without a license by perceived race",
  tooltip_text = tooltip_text,
  caption = caption_text,
  export_data_label = list(pointFormat='{point.rate:.1f}%') 
)

```

```{r, echo=FALSE}

chart

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>