---
title: ""
output:
  html_document:
    includes:
      in_header: "../header.html"
    mathjax: null
---

```{r, include=FALSE}
# Check if document is being run as a child, if yes don't apply styling again
is_child <- !is.null(knitr::opts_knit$get("parent.frame"))
if (is_child) {
  knitr::opts_chunk$set(include = FALSE)
}
```

```{r, include=FALSE}
# set up -----------------------------
library(RPostgreSQL)
library(devtools)
# remotes::install_github("catalystcalifornia/rdaCharts", upgrade="never") 
library(rdaCharts)
library(htmltools) 

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

  
# pull and clean analysis tables for visualizing ----
df_p<-dbGetQuery(con, "SELECT * FROM report_traffic_uof")

dbDisconnect(con)

# filter groups being visualized and select rate and counts to be visualized
df<-df_p%>%  
  select(race,gender,uof_count,uof_total,uof_total_rate)%>%
  mutate(race_label=case_when(
    race == 'latinx' ~ "Person of Color", 
    race =='nh_white' ~ 'White',
    race =='nh_black' ~ 'Person of Color',
    race == 'nh_asian' ~ 'Person of Color',
   race == 'nh_multiracial' ~ 'Person of Color',
    race == 'nh_aian' ~ 'Person of Color',
    race == 'nh_nhpi' ~ 'Person of Color',
    race == 'nh_sswana' ~ 'Person of Color', 
    TRUE ~ as.character(race)))

df<-df%>%
  group_by(race_label,gender)%>%
  summarise(uof_count=sum(uof_count),
            uof_rate=sum(uof_count)/min(uof_total)*100,
            uof_total=min(uof_total),.groups='drop')%>%
  filter(uof_rate>0)%>%
  mutate(label=case_when(
    race_label=="Person of Color" ~paste0(gender, "s of Color"),
    race_label=="White" ~paste0(race_label, " ",gender, "s"),
    TRUE ~as.character(race_label)),
         x="Uses of Force")%>%
  arrange(race_label,-uof_rate)

# add factors for sorting
df <- within(df, label <- factor(label, levels=c("White Males", "White Females", "Females of Color", "Males of Color"))) 

# visualize--------------------------
# create caption 
sourcenote<-"Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis covers all officer-initiated traffic stops in 2022 where an officer used force against a person. Genders are based identification by officers. According to the data source, officers reported no uses of force against people perceived as transgender or gender nonconforming."

racenote <- "Race/ethnicity: Person of color includes any person perceived as non-White."

caption_text <- paste(sourcenote, methodnote,racenote)

# create tooltip text
tooltip_text <- "Fresno PD used force against {point.uof_total} people during officer-initiated traffic stops. <b>{point.uof_rate:.1f}%</b> of these people were perceived as <b>{point.label}</b> by officers."
```

```{r, include=FALSE}
# Visualizing as table --------------------------
chart_race<-rdaStackedBar(df,
                          "x",
                          "uof_rate",
                          "label",
                          theme="theme_fbhc",
                          bar_colors = c("#98999D", "#BABBBF", "#FED163", "#FDB913"),
  title="Fresno PD Uses Force Mostly Against Men of Color",
  subtitle=" Percent of people subjected to officer use of force during traffic stops by perceived race",
  tooltip_text=tooltip_text,
  caption=caption_text,
  export_data_label=list(pointFormat='{point.uof_rate:.1f}%'))

```

```{r, echo=FALSE}

chart_race

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>
