---
title: ""
output:
  html_document:
    includes:
      in_header: header.html
---

```{r, include=FALSE}
# Generate header.html with CSS if running standalone
if (is.null(knitr::opts_knit$get("child"))) {
  css_content <- readLines("../fbhc_brandguide.css")
  writeLines(paste0("<style>\n", paste(css_content, collapse="\n"), "\n</style>"), "header.html")
} else {
  writeLines("", "header.html")  # Empty file if running as child
}
```

```{r, include=FALSE}

# set up -----------------------------
library(RPostgreSQL)
library(devtools)
# remotes::install_github("catalystcalifornia/rdaCharts", upgrade="never") 
library(rdaCharts)
library(stringr)

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# pull analysis table for visualizing
df<-dbGetQuery(con, "SELECT * FROM report_traffic_result_person")%>%
  mutate(stop_result_simple = str_to_title(stop_result_simple))

# Combine stop results that are under .5% to 'Other' category
df <- df%>%
  mutate(stop_result_simple=ifelse(rate<=0.5, "Other Stop Result", stop_result_simple),
        count=ifelse(rate<=0.5, sum(count[rate<=0.5]), count),
        rate=count/total*100)%>%
  slice(1:6)


# visualize--------------------------
# create caption 
sourcenote<-"Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made by officers in 2022. Stop results that had a rate of 0.5% or less were combined and defined as 'Other Stop Result in this data visualization.'"

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption_text <- paste(sourcenote, methodnote)

# create tooltip text

tooltip_text <- "Out of 100 people stopped in traffic stops,  <b>{point.rate:.1f}%</b> of people were given a stop result of <b>{point.stop_result_simple}</b>, or a total of <b>{point.count:.0f}</b> people."


# run function
chart <-rdaBar(
  df,
  "stop_result_simple",
  "rate",
  theme="theme_fbhc",
  title = "The Majority of Traffic Stops Made by Fresno PD Result in a Citation",
  subtitle = "Percent of officer-initiated traffic stops by stop result",
  tooltip_text = tooltip_text,
  caption = caption_text,
  export_data_label = list(pointFormat='{point.rate:.1f}%')
)


```

```{r, echo=FALSE}

chart

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>