---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\fbhc_brandguide.css"
---
<!-- link to Adobe Fonts (Source Serif Pro, Montserrat, Open Sans) -->
<link rel="stylesheet" href="https://use.typekit.net/kjp5mnx.css">

```{r, include=FALSE}

# set up -----------------------------
library(RPostgreSQL)
library(devtools)
remotes::install_github("catalystcalifornia/rdaCharts", upgrade="never") 
# library(rdaCharts)
library(stringr)

#connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")

con <- connect_to_db("eci_fresno_ripa")

# Manually create the budget data as a df
## reference (from My):

df_budget <- data.frame(
  fund_description  = c("FPD General Fund Operating Budget ",
"PARCS General fund Operating Budget ",
"FPD Total Budget",
"PARCS Total Budget "
),

budget = c( 255932800, 20918800, 288364100, 155293200 
)
)



# visualize--------------------------
# create caption 
sourcenote<-"Catalyst California's calculations based on City of Fresno's Police Stop Data (2022), catalystcalifornia.org, 2024. "

methodnote <- "Analysis for all officer-initiated traffic stops made by officers in 2022. Stop results that had a rate of 0.5% or less were combined and defined as 'Other Stop Result in this data visualization.'"

racenote <- "Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, SWANA/SA=Southwest Asian (Middle Eastern) or North African, or South Asian."

caption <- paste("<br>", sourcenote, methodnote)

# create tooltip text

tooltip_text <- "Out of 100 people stopped in traffic stops,  <b>{point.rate:.1f}%</b> of people were given a stop result of <b>{point.stop_result_simple}</b>, or a total of <b>{point.count:.0f}</b> people."


# run function
chart <-rdaBar(
  df_budget,
  "fund_description",
   "budget",
  theme="theme_fbhc",
  title = "The Majority of Traffic Stops Made by Fresno PD Result in a Citation",
  subtitle = "Percent of officer-initiated traffic stops by stop result",
  tooltip_text = tooltip_text,
  caption = caption_text,
  export_data_label = list(pointFormat='{point.rate:.1f}%')
)


## Manually create bar graph -----------------------------

# set parameters

title <- "Fresno PD gets 12 times more General Operating Funds than Parks, Libraries, and othe Community Programs combined "

subtitle <-"FY25 Proposed Budget Allocation Comparative Analysis for Police versus PARCS"

# create tooltip text

tooltip_text <- "<b>{point.df_budget$budget:.1f}$</b> is allocated to <b>{point.df_budget$fund_description}</b> in 2025."

export_data_label <- "list(pointFormat='{point.rate:.1f}%')" 
  
# get themes
 
data(theme_options)
list2env(theme_options, envir = .GlobalEnv)

colors<- c("#FDB913", "#053451")
  
# graph 

highchart() %>%
# 
#     hc_add_series(df_budget,
#                "bar",
#                name="",
#                hcaes(x = fund_description,
#                      y = budget))%>%
   hc_chart(type = "bar") %>%
  hc_xAxis(categories = df_budget$fund_description) %>%
       hc_add_series(
    data = lapply(seq_along(df_budget$budget), function(i) {
      list(y = df_budget$budget[i], color = colors[(i %% 2) + 1])
    }),
    name = ""
  )%>%

    hc_tooltip(headerFormat='', # removes series label from top of tooltip
               pointFormat = "<b>{point.x}$</b> is allocated to <b>{point.y}</b> in 2025.",
               useHTML=TRUE) %>%  # allows tooltip to read <br> html in reformatted tooltip_text

    hc_title(text = title,
             style = list(useHTML = TRUE)) %>%

    hc_subtitle(text = subtitle) %>%

    hc_caption(text = caption) %>%

    hc_yAxis(title = list(text = paste0(""))) %>%

    hc_xAxis(title = list(text = paste0(""),
                          labels=list(position="bottom")),
             type = "category") %>%

    hc_legend(enabled=FALSE) %>%

     hc_add_theme(theme_fbhc) %>%
  
   hc_colors(colors = c("#FDB913", "#053451", "#FDB913", "#053451"))%>%

    hc_chart(marginRight=120) %>%

    hc_exporting(
      enabled = TRUE,
      sourceWidth=900,
      sourceHeight=600,
      chartOptions=list(plotOptions=list(
        series=list(
          dataLabels=list(
            enabled=TRUE,
            format=paste0(export_data_label))))),
      filename = paste0(subtitle,"_Catalyst California, catalystcalifornia.org, ", format(Sys.Date(), "%Y"), "."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV')))
    )


```

```{r, echo=FALSE}

chart

```
<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>